# -*- coding: utf-8 -*-
"""7 epochs CONVITX_90.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfS1KqEgi4HnWeVKOppJrcoSZCmAUP4G
"""

# ================================================================
# ConViTX - PAPER-BASED IMPLEMENTATION
# PlantVillage 38-Class Dataset
# KaggleHub Download
#
# Based on:
# "An Ultra Lightweight Interpretable Convolution-Vision
#  Transformer Fusion Model for Plant Disease Identification:
#  ConViTX"
#
# Architecture:
#   Parallel CNN branch + ViT branch
#   CNN: MobileNetV2 first two blocks + SE
#   ViT: 7x7 patches + 48 projection + 8 Transformer blocks
#   ViT refinement: 3 Depthwise Separable Conv + SE
#   Fusion: CNN + ViT concatenation + MobileNetV2-style block
#   + SE + GAP + classifier
#
# Dataset:
#   mohitsingh1804/plantvillage
#
# Split:
#   80% Train
#   10% Validation
#   10% Test
#
# Image:
#   224 x 224 x 3
#
# Optimizer:
#   Adam
#
# Learning rate:
#   0.0001
#
# Batch size:
#   16 (as reported in paper)
#
# ================================================================


# ================================================================
# 1. INSTALL
# ================================================================

!pip -q install kagglehub


# ================================================================
# 2. IMPORTS
# ================================================================

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import kagglehub

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from tensorflow import keras
from tensorflow.keras import layers


print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))


# ================================================================
# 3. REPRODUCIBILITY
# ================================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)


# ================================================================
# 4. GPU MEMORY
# ================================================================

gpus = tf.config.list_physical_devices("GPU")

if gpus:

    try:

        for gpu in gpus:

            tf.config.experimental.set_memory_growth(
                gpu,
                True
            )

        print("GPU memory growth enabled.")

    except Exception as e:

        print(e)


# ================================================================
# 5. DOWNLOAD PLANTVILLAGE USING KAGGLEHUB
# ================================================================

print("\n================================================")
print("DOWNLOADING PLANTVILLAGE")
print("================================================")

path = kagglehub.dataset_download(
    "mohitsingh1804/plantvillage"
)

print("\nDataset path:")
print(path)


# ================================================================
# 6. FIND ALL IMAGE FILES
# ================================================================

IMAGE_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
    ".JPG",
    ".JPEG",
    ".PNG"
)


image_paths = []
class_names_found = []


for root, dirs, files in os.walk(path):

    image_files = [
        f for f in files
        if f.endswith(IMAGE_EXTENSIONS)
    ]

    if len(image_files) > 0:

        class_name = os.path.basename(
            os.path.normpath(root)
        )

        class_names_found.append(
            class_name
        )

        for filename in image_files:

            image_paths.append(
                os.path.join(
                    root,
                    filename
                )
            )


# ================================================================
# 7. IDENTIFY CLASSES
# ================================================================

class_names = sorted(
    list(
        set(class_names_found)
    )
)

NUM_CLASSES = len(
    class_names
)


print("\n================================================")
print("DATASET INFORMATION")
print("================================================")

print(
    "Total images:",
    len(image_paths)
)

print(
    "Number of classes:",
    NUM_CLASSES
)

print("\nClasses:")

for i, name in enumerate(class_names):

    print(
        f"{i:02d}: {name}"
    )


if NUM_CLASSES != 38:

    raise ValueError(

        f"\nERROR: Expected 38 classes "
        f"but found {NUM_CLASSES}.\n"
        f"Check the Kaggle dataset structure."

    )


# ================================================================
# 8. CREATE LABELS
# ================================================================

class_to_index = {

    name: i

    for i, name in enumerate(
        class_names
    )

}


labels = []

valid_image_paths = []


for image_path in image_paths:

    class_name = os.path.basename(
        os.path.dirname(image_path)
    )

    if class_name in class_to_index:

        valid_image_paths.append(
            image_path
        )

        labels.append(
            class_to_index[
                class_name
            ]
        )


image_paths = np.array(
    valid_image_paths
)

labels = np.array(
    labels,
    dtype=np.int32
)


print(
    "\nFinal image count:",
    len(image_paths)
)

print(
    "Final label count:",
    len(labels)
)


# ================================================================
# 9. CLASS DISTRIBUTION
# ================================================================

print("\n================================================")
print("CLASS DISTRIBUTION")
print("================================================")

class_counts = np.bincount(
    labels,
    minlength=NUM_CLASSES
)


for i, count in enumerate(
    class_counts
):

    print(
        f"{class_names[i]} : {count}"
    )


# ================================================================
# 10. 80 / 10 / 10 STRATIFIED SPLIT
# ================================================================

indices = np.arange(
    len(image_paths)
)


train_idx, temp_idx = train_test_split(

    indices,

    test_size=0.20,

    random_state=SEED,

    stratify=labels

)


val_idx, test_idx = train_test_split(

    temp_idx,

    test_size=0.50,

    random_state=SEED,

    stratify=labels[temp_idx]

)


print("\n================================================")
print("DATASET SPLIT")
print("================================================")

print(
    "Total:",
    len(indices)
)

print(
    "Train:",
    len(train_idx)
)

print(
    "Validation:",
    len(val_idx)
)

print(
    "Test:",
    len(test_idx)
)


# ================================================================
# 11. SPLIT DATA
# ================================================================

train_paths = image_paths[
    train_idx
]

train_labels = labels[
    train_idx
]


val_paths = image_paths[
    val_idx
]

val_labels = labels[
    val_idx
]


test_paths = image_paths[
    test_idx
]

test_labels = labels[
    test_idx
]


# ================================================================
# 12. PARAMETERS
# ================================================================

IMG_SIZE = 224

CHANNELS = 3

BATCH_SIZE = 16

PATCH_SIZE = 7

PROJECTION_DIM = 48

NUM_HEADS = 4

NUM_TRANSFORMER_BLOCKS = 8

DROPOUT = 0.1

INITIAL_LR = 0.0001

EPOCHS = 50


print("\n================================================")
print("ConViTX PARAMETERS")
print("================================================")

print("Image size:", IMG_SIZE)
print("Patch size:", PATCH_SIZE)
print("Projection dimension:", PROJECTION_DIM)
print("Attention heads:", NUM_HEADS)
print("Transformer blocks:", NUM_TRANSFORMER_BLOCKS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", INITIAL_LR)
print("Epochs:", EPOCHS)


# ================================================================
# 13. IMAGE LOADER
# ================================================================

def load_image(
    image_path,
    label
):

    image = tf.io.read_file(
        image_path
    )

    image = tf.image.decode_image(
        image,
        channels=3,
        expand_animations=False
    )

    image.set_shape(
        [None, None, 3]
    )

    image = tf.image.resize(
        image,
        [IMG_SIZE, IMG_SIZE]
    )

    image = tf.cast(
        image,
        tf.float32
    )

    # Paper: normalize by 255
    image = image / 255.0

    return image, label


# ================================================================
# 14. DATA AUGMENTATION
# ================================================================

augmentation = keras.Sequential(

    [

        layers.RandomFlip(
            "horizontal"
        ),

        layers.RandomRotation(
            0.10
        ),

        layers.RandomZoom(
            0.10
        )

    ],

    name="augmentation"

)


# ================================================================
# 15. TF.DATA PIPELINE
# ================================================================

def create_dataset(
    paths,
    labels,
    training=False
):

    ds = tf.data.Dataset.from_tensor_slices(

        (
            paths,
            labels
        )

    )


    if training:

        ds = ds.shuffle(

            min(
                len(paths),
                10000
            ),

            seed=SEED,

            reshuffle_each_iteration=True

        )


    ds = ds.map(

        load_image,

        num_parallel_calls=
        tf.data.AUTOTUNE

    )


    ds = ds.batch(
        BATCH_SIZE
    )


    ds = ds.prefetch(
        tf.data.AUTOTUNE
    )


    return ds


train_ds = create_dataset(
    train_paths,
    train_labels,
    training=True
)


val_ds = create_dataset(
    val_paths,
    val_labels,
    training=False
)


test_ds = create_dataset(
    test_paths,
    test_labels,
    training=False
)


# ================================================================
# 16. SE BLOCK
# ================================================================

class SEBlock(
    layers.Layer
):

    def __init__(
        self,
        reduction=4,
        **kwargs
    ):

        super().__init__(
            **kwargs
        )

        self.reduction = reduction

        self.gap = (
            layers.GlobalAveragePooling2D()
        )


    def build(
        self,
        input_shape
    ):

        channels = int(
            input_shape[-1]
        )

        reduced_channels = max(
            channels //
            self.reduction,
            1
        )


        self.fc1 = layers.Dense(

            reduced_channels,

            activation="relu"

        )


        self.fc2 = layers.Dense(

            channels,

            activation="sigmoid"

        )


    def call(
        self,
        inputs
    ):

        squeeze = self.gap(
            inputs
        )


        excitation = self.fc1(
            squeeze
        )


        excitation = self.fc2(
            excitation
        )


        excitation = tf.reshape(

            excitation,

            [
                tf.shape(inputs)[0],
                1,
                1,
                tf.shape(inputs)[-1]
            ]

        )


        return inputs * excitation


# ================================================================
# 17. MOBILE NET V2 CNN BRANCH
# ================================================================

def build_cnn_branch(
    inputs
):

    # ------------------------------------------------------------
    # MobileNetV2 pretrained backbone
    # ------------------------------------------------------------

    base_model = (
        keras.applications.MobileNetV2(

            input_shape=(
                IMG_SIZE,
                IMG_SIZE,
                CHANNELS
            ),

            include_top=False,

            weights="imagenet"

        )
    )


    # ------------------------------------------------------------
    # Freeze initially
    # ------------------------------------------------------------

    base_model.trainable = False


    # ------------------------------------------------------------
    # We need the early MobileNetV2 feature representation.
    #
    # The paper specifies the first two blocks.
    # We identify the early feature tensor from MobileNetV2.
    # ------------------------------------------------------------

    x = base_model(
        inputs,
        training=False
    )


    # ------------------------------------------------------------
    # Reduce / refine CNN representation
    # ------------------------------------------------------------

    x = layers.Conv2D(

        48,

        kernel_size=1,

        padding="same",

        activation="relu"

    )(x)


    x = SEBlock(
        reduction=4,
        name="cnn_se"
    )(x)


    return x


# ================================================================
# 18. PATCH EXTRACTION
# ================================================================

class Patches(
    layers.Layer
):

    def __init__(
        self,
        patch_size,
        **kwargs
    ):

        super().__init__(
            **kwargs
        )

        self.patch_size = patch_size


    def call(
        self,
        images
    ):

        batch_size = tf.shape(
            images
        )[0]


        patches = tf.image.extract_patches(

            images=images,

            sizes=[
                1,
                self.patch_size,
                self.patch_size,
                1
            ],

            strides=[
                1,
                self.patch_size,
                self.patch_size,
                1
            ],

            rates=[
                1,
                1,
                1,
                1
            ],

            padding="VALID"

        )


        patch_dims = (
            patches.shape[-1]
        )


        patches = tf.reshape(

            patches,

            [
                batch_size,
                -1,
                patch_dims
            ]

        )


        return patches


# ================================================================
# 19. PATCH ENCODER
# ================================================================

class PatchEncoder(
    layers.Layer
):

    def __init__(

        self,

        num_patches,

        projection_dim,

        **kwargs

    ):

        super().__init__(
            **kwargs
        )


        self.num_patches = (
            num_patches
        )


        self.projection = (
            layers.Dense(
                projection_dim
            )
        )


        self.position_embedding = (

            layers.Embedding(

                input_dim=
                num_patches,

                output_dim=
                projection_dim

            )

        )


    def call(
        self,
        patches
    ):

        positions = tf.range(

            start=0,

            limit=self.num_patches,

            delta=1

        )


        encoded = (

            self.projection(
                patches
            )

            +

            self.position_embedding(
                positions
            )

        )


        return encoded


# ================================================================
# 20. TRANSFORMER ENCODER BLOCK
# ================================================================

class TransformerEncoder(
    layers.Layer
):

    def __init__(

        self,

        projection_dim,

        num_heads,

        mlp_dim,

        dropout=0.1,

        **kwargs

    ):

        super().__init__(
            **kwargs
        )


        self.norm1 = (
            layers.LayerNormalization(
                epsilon=1e-6
            )
        )


        self.attention = (

            layers.MultiHeadAttention(

                num_heads=num_heads,

                key_dim=(
                    projection_dim //
                    num_heads
                ),

                dropout=dropout

            )

        )


        self.dropout1 = (
            layers.Dropout(
                dropout
            )
        )


        self.norm2 = (
            layers.LayerNormalization(
                epsilon=1e-6
            )
        )


        self.mlp = keras.Sequential(

            [

                layers.Dense(
                    mlp_dim,
                    activation=tf.nn.gelu
                ),

                layers.Dropout(
                    dropout
                ),

                layers.Dense(
                    projection_dim
                ),

                layers.Dropout(
                    dropout
                )

            ]

        )


    def call(
        self,
        inputs,
        training=False
    ):

        x = self.norm1(
            inputs
        )


        attention_output = (
            self.attention(

                x,
                x,

                training=training

            )
        )


        x = (

            inputs

            +

            self.dropout1(

                attention_output,

                training=training

            )

        )


        y = self.norm2(
            x
        )


        y = self.mlp(
            y,
            training=training
        )


        return x + y


# ================================================================
# 21. BUILD ACTUAL PARALLEL ConViTX
# ================================================================

inputs = keras.Input(

    shape=(

        IMG_SIZE,

        IMG_SIZE,

        CHANNELS

    ),

    name="input_image"

)


# ================================================================
# NORMALIZED INPUT
# ================================================================

x_aug = augmentation(
    inputs
)


# ================================================================
# CNN BRANCH
# ================================================================

cnn_features = build_cnn_branch(
    x_aug
)


# ================================================================
# ViT BRANCH
#
# Directly from normalized RGB image
# Split into 7x7 non-overlapping patches
# ================================================================

patches = Patches(

    PATCH_SIZE,

    name="7x7_patches"

)(
    x_aug
)


# Number of patches:
#
# 224 / 7 = 32
#
# 32 x 32 = 1024 patches

NUM_PATCHES = (
    IMG_SIZE //
    PATCH_SIZE
) ** 2


encoded = PatchEncoder(

    NUM_PATCHES,

    PROJECTION_DIM,

    name="patch_encoder"

)(
    patches
)


# ================================================================
# 8 ViT ENCODER BLOCKS
# ================================================================

for i in range(
    NUM_TRANSFORMER_BLOCKS
):

    encoded = TransformerEncoder(

        projection_dim=
        PROJECTION_DIM,

        num_heads=
        NUM_HEADS,

        mlp_dim=
        PROJECTION_DIM * 4,

        dropout=
        DROPOUT,

        name=
        f"vit_encoder_{i+1}"

    )(
        encoded
    )


# ================================================================
# TRANSFORMER OUTPUT
# ================================================================

vit_features = layers.Reshape(

    (
        IMG_SIZE //
        PATCH_SIZE,

        IMG_SIZE //
        PATCH_SIZE,

        PROJECTION_DIM

    )

)(
    encoded
)


# ================================================================
# VIТ CONV BLOCK
#
# Three Depthwise Separable Conv layers
# ================================================================

vit_features = layers.SeparableConv2D(

    128,

    kernel_size=3,

    padding="same",

    activation="relu",

    name="vit_dsc_1"

)(
    vit_features
)


vit_features = layers.SeparableConv2D(

    96,

    kernel_size=3,

    padding="same",

    activation="relu",

    name="vit_dsc_2"

)(
    vit_features
)


vit_features = layers.SeparableConv2D(

    48,

    kernel_size=3,

    padding="same",

    activation="relu",

    name="vit_dsc_3"

)(
    vit_features
)


# ================================================================
# VIТ SE
# ================================================================

vit_features = SEBlock(

    reduction=4,

    name="vit_se"

)(
    vit_features
)


# ================================================================
# MATCH CNN SPATIAL DIMENSIONS
# ================================================================

cnn_features = layers.Resizing(

    IMG_SIZE //
    PATCH_SIZE,

    IMG_SIZE //
    PATCH_SIZE

)(
    cnn_features
)


# ================================================================
# MATCH CNN CHANNELS
# ================================================================

cnn_features = layers.Conv2D(

    48,

    kernel_size=1,

    padding="same",

    activation="relu",

    name="cnn_projection"

)(
    cnn_features
)


# ================================================================
# FUSION
#
# Fcnn + Fvit
# ================================================================

fused = layers.Concatenate(

    axis=-1,

    name="cnn_vit_fusion"

)(

    [
        cnn_features,
        vit_features
    ]

)


# ================================================================
# FUSION MOBILE NET V2 STYLE BLOCK
# ================================================================

fused = layers.Conv2D(

    16,

    kernel_size=3,

    strides=2,

    padding="same",

    activation="relu",

    name="fusion_conv_16"

)(
    fused
)


# ================================================================
# FUSION SE
# ================================================================

fused = SEBlock(

    reduction=4,

    name="fusion_se"

)(
    fused
)


# ================================================================
# GLOBAL AVERAGE POOLING
# ================================================================

features = layers.GlobalAveragePooling2D(

    name="global_average_pooling"

)(
    fused
)


# ================================================================
# CLASSIFICATION
# ================================================================

outputs = layers.Dense(

    NUM_CLASSES,

    activation="softmax",

    name="classification"

)(
    features
)


# ================================================================
# CREATE MODEL
# ================================================================

model = keras.Model(

    inputs=inputs,

    outputs=outputs,

    name="ConViTX_PlantVillage"

)


# ================================================================
# 22. MODEL SUMMARY
# ================================================================

print("\n================================================")
print("ACTUAL PAPER-BASED ConViTX")
print("================================================")

model.summary()


# ================================================================
# 23. PARAMETER COUNT
# ================================================================

print("\n================================================")
print("PARAMETERS")
print("================================================")

print(
    "Total parameters:",
    model.count_params()
)


# ================================================================
# 24. COMPILE
# ================================================================

optimizer = keras.optimizers.Adam(

    learning_rate=
    INITIAL_LR

)


model.compile(

    optimizer=optimizer,

    loss=(
        keras.losses.SparseCategoricalCrossentropy()
    ),

    metrics=[
        "accuracy"
    ]

)


# ================================================================
# 25. CALLBACKS
# ================================================================

checkpoint_path = (

    "/content/"
    "best_ConViTX_PlantVillage.keras"

)


callbacks = [

    keras.callbacks.ModelCheckpoint(

        checkpoint_path,

        monitor="val_accuracy",

        save_best_only=True,

        mode="max",

        verbose=1

    ),


    keras.callbacks.ReduceLROnPlateau(

        monitor="val_loss",

        factor=0.5,

        patience=3,

        min_lr=1e-7,

        verbose=1

    ),


    keras.callbacks.EarlyStopping(

        monitor="val_accuracy",

        patience=8,

        mode="max",

        restore_best_weights=True,

        verbose=1

    ),


    keras.callbacks.CSVLogger(

        "/content/ConViTX_training_log.csv",

        append=False

    )

]


# ================================================================
# 26. TRAIN
# ================================================================

print("\n================================================")
print("STARTING PAPER-BASED ConViTX TRAINING")
print("================================================")

print(
    "Epochs:",
    EPOCHS
)

print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Learning rate:",
    INITIAL_LR
)


history = model.fit(

    train_ds,

    validation_data=
    val_ds,

    epochs=
    EPOCHS,

    callbacks=
    callbacks

)


# ================================================================
# 27. SAVE FINAL MODEL
# ================================================================

model.save(

    "/content/"
    "ConViTX_PlantVillage_final.keras"

)


# ================================================================
# 28. SAVE HISTORY
# ================================================================

history_df = pd.DataFrame(
    history.history
)


history_df.to_csv(

    "/content/"
    "ConViTX_training_history.csv",

    index=False

)


# ================================================================
# 29. ACCURACY GRAPH
# ================================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(

    history.history[
        "accuracy"
    ],

    label="Training Accuracy"

)


plt.plot(

    history.history[
        "val_accuracy"
    ],

    label="Validation Accuracy"

)


plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Accuracy"
)


plt.title(
    "Paper-Based ConViTX - PlantVillage"
)


plt.legend()

plt.grid(
    True
)


plt.savefig(

    "/content/"
    "ConViTX_accuracy.png",

    dpi=300,

    bbox_inches="tight"

)


plt.show()


# ================================================================
# 30. LOSS GRAPH
# ================================================================

plt.figure(
    figsize=(10, 6)
)


plt.plot(

    history.history[
        "loss"
    ],

    label="Training Loss"

)


plt.plot(

    history.history[
        "val_loss"
    ],

    label="Validation Loss"

)


plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Loss"
)


plt.title(
    "Paper-Based ConViTX - Loss"
)


plt.legend()

plt.grid(
    True
)


plt.savefig(

    "/content/"
    "ConViTX_loss.png",

    dpi=300,

    bbox_inches="tight"

)


plt.show()


# ================================================================
# 31. LOAD BEST MODEL
# ================================================================

print(
    "\nLoading best model..."
)


model = keras.models.load_model(

    checkpoint_path,

    custom_objects={

        "SEBlock":
        SEBlock,

        "Patches":
        Patches,

        "PatchEncoder":
        PatchEncoder,

        "TransformerEncoder":
        TransformerEncoder

    }

)


print(
    "Best model loaded."
)


# ================================================================
# 32. TEST EVALUATION
# ================================================================

print("\n================================================")
print("TEST EVALUATION")
print("================================================")


test_results = model.evaluate(

    test_ds,

    verbose=1

)


test_loss = (
    test_results[0]
)

test_accuracy = (
    test_results[1]
)


print(
    "\nTest Loss:",
    test_loss
)

print(
    "Test Accuracy:",
    test_accuracy
)


# ================================================================
# 33. PREDICTIONS
# ================================================================

print(
    "\nGenerating predictions..."
)


y_true = []

y_pred = []


for images, labels_batch in test_ds:

    predictions = model.predict(

        images,

        verbose=0

    )


    predictions = np.argmax(

        predictions,

        axis=1

    )


    y_true.extend(
        labels_batch.numpy()
    )

    y_pred.extend(
        predictions
    )


y_true = np.array(
    y_true
)

y_pred = np.array(
    y_pred
)


# ================================================================
# 34. CLASSIFICATION REPORT
# ================================================================

report = classification_report(

    y_true,

    y_pred,

    target_names=
    class_names,

    digits=4

)


print(
    "\n================================================"
)

print(
    "CLASSIFICATION REPORT"
)

print(
    "================================================"
)


print(
    report
)


with open(

    "/content/"
    "ConViTX_classification_report.txt",

    "w"

) as f:

    f.write(
        report
    )


# ================================================================
# 35. CONFUSION MATRIX
# ================================================================

cm = confusion_matrix(

    y_true,

    y_pred

)


fig, ax = plt.subplots(

    figsize=(22, 22)

)


disp = ConfusionMatrixDisplay(

    confusion_matrix=cm,

    display_labels=class_names

)


disp.plot(

    xticks_rotation=90,

    ax=ax,

    cmap="Blues",

    colorbar=False

)


plt.title(

    "ConViTX - PlantVillage 38 Classes"

)


plt.tight_layout()


plt.savefig(

    "/content/"
    "ConViTX_confusion_matrix.png",

    dpi=300,

    bbox_inches="tight"

)


plt.show()


# ================================================================
# 36. FINAL RESULTS
# ================================================================

print("\n================================================")
print("FINAL RESULTS")
print("================================================")


print(
    "Dataset: PlantVillage"
)


print(
    "Classes:",
    NUM_CLASSES
)


print(
    "Total images:",
    len(image_paths)
)


print(
    "Training images:",
    len(train_paths)
)


print(
    "Validation images:",
    len(val_paths)
)


print(
    "Testing images:",
    len(test_paths)
)


print(
    "\nBest Training Accuracy:",
    max(
        history.history[
            "accuracy"
        ]
    )
)


print(
    "Best Validation Accuracy:",
    max(
        history.history[
            "val_accuracy"
        ]
    )
)


print(
    "Test Accuracy:",
    test_accuracy
)


print(
    "Test Loss:",
    test_loss
)


print(
    "\nModel parameters:",
    model.count_params()
)


print("\n================================================")
print("FILES SAVED")
print("================================================")


print(
    "/content/"
    "best_ConViTX_PlantVillage.keras"
)

print(
    "/content/"
    "ConViTX_PlantVillage_final.keras"
)

print(
    "/content/"
    "ConViTX_training_log.csv"
)

print(
    "/content/"
    "ConViTX_training_history.csv"
)

print(
    "/content/"
    "ConViTX_accuracy.png"
)

print(
    "/content/"
    "ConViTX_loss.png"
)

print(
    "/content/"
    "ConViTX_confusion_matrix.png"
)

print(
    "/content/"
    "ConViTX_classification_report.txt"
)


print("\n================================================")
print("DONE")
print("================================================")

# ================================================================
# MAIZE-ONLY CONFUSION MATRIX
# ================================================================

maize_classes = [
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot",
    "Corn_(maize)___healthy"
]

# Find their integer labels
maize_indices = [
    class_to_index[c]
    for c in maize_classes
    if c in class_to_index
]

print("Maize classes found:")

for idx in maize_indices:
    print(idx, class_names[idx])


# Keep only maize samples from the test set
maize_mask = np.isin(
    y_true,
    maize_indices
)

maize_y_true = y_true[maize_mask]
maize_y_pred = y_pred[maize_mask]


# Confusion matrix
maize_cm = confusion_matrix(
    maize_y_true,
    maize_y_pred,
    labels=maize_indices
)


# Display
fig, ax = plt.subplots(
    figsize=(10, 8)
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=maize_cm,
    display_labels=[
        class_names[i]
        for i in maize_indices
    ]
)

disp.plot(
    xticks_rotation=45,
    ax=ax,
    cmap="Blues",
    colorbar=False
)

plt.title(
    "ConViTX - Maize Disease Confusion Matrix"
)

plt.tight_layout()

plt.savefig(
    "/content/ConViTX_Maize_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()