# -*- coding: utf-8 -*-
"""CONVITX_89

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmCvcVSf1ByyLmPbGFixZBkGv2iElgU5
"""

!pip -q install lime
!pip -q install scikit-image

import os
import cv2
import zipfile
import random
import warnings
import numpy as np
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import backend as K

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    auc,
    average_precision_score
)

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator

ZIP_PATH = "/content/Potato.zip"

IMG_SIZE = 224

BATCH_SIZE = 32

EPOCHS = 30

def segment_leaf(image):

    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

    lower = np.array([25,40,40])

    upper = np.array([95,255,255])

    mask = cv2.inRange(hsv, lower, upper)

    kernel = np.ones((5,5), np.uint8)

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    result = cv2.bitwise_and(image, image, mask=mask)

    return result

with zipfile.ZipFile(ZIP_PATH,"r") as z:

    imgs = [f for f in z.namelist()

            if f.lower().endswith((".jpg",".jpeg",".png"))]

    sample = imgs[0]

    data = z.read(sample)

    arr = np.frombuffer(data,np.uint8)

    img = cv2.imdecode(arr,cv2.IMREAD_COLOR)

    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

seg = segment_leaf(img)

plt.figure(figsize=(10,5))

plt.subplot(121)

plt.imshow(img)

plt.title("Original")

plt.axis("off")

plt.subplot(122)

plt.imshow(seg)

plt.title("Segmented")

plt.axis("off")

plt.show()

with zipfile.ZipFile(ZIP_PATH,"r") as z:

    files = z.namelist()

print("Total Files :", len(files))

print()

for i in files[:20]:

    print(i)

# ==========================================================
# Read Complete Dataset From ZIP
# ==========================================================

images = []
labels = []

with zipfile.ZipFile(ZIP_PATH, "r") as z:

    image_files = [
        f for f in z.namelist()
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    print("Total image files found:", len(image_files))

    for file in image_files:

        if file.endswith("/"):
            continue

        if "__MACOSX" in file:
            continue

        parts = file.replace("\\", "/").split("/")

        # Skip images not inside a class folder
        if len(parts) < 2:
            continue

        class_name = parts[-2]

        try:

            img_bytes = z.read(file)

            img_array = np.frombuffer(img_bytes, np.uint8)

            img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

            if img is None:
                continue

            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            img = segment_leaf(img)

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

            images.append(img)

            labels.append(class_name)

        except Exception:
            continue

print("Images Loaded :", len(images))

# ==========================================================
# Convert To NumPy
# ==========================================================

images = np.array(images, dtype=np.float32)

labels = np.array(labels)

print(images.shape)

print(labels.shape)

# ==========================================================
# Dataset Summary
# ==========================================================

unique_classes = sorted(np.unique(labels))

print("Classes Found:\n")

for cls in unique_classes:

    print(cls)

print()

print("Number of Classes :", len(unique_classes))

# ==========================================================
# Display Random Images
# ==========================================================

plt.figure(figsize=(12,12))

for i in range(9):

    idx = random.randint(0, len(images)-1)

    plt.subplot(3,3,i+1)

    plt.imshow(images[idx].astype(np.uint8))

    plt.title(labels[idx])

    plt.axis("off")

plt.tight_layout()

plt.show()

# ==========================================================
# MobileNetV2 Preprocessing
# ==========================================================

images = tf.keras.applications.mobilenet_v2.preprocess_input(images)

print(images.shape)

# ==========================================================
# Label Encoding
# ==========================================================

encoder = LabelEncoder()

labels_encoded = encoder.fit_transform(labels)

NUM_CLASSES = len(encoder.classes_)

labels_encoded = to_categorical(
    labels_encoded,
    NUM_CLASSES
)

print("Classes")

print(encoder.classes_)

print()

print("Number of Classes :", NUM_CLASSES)

# ==========================================================
# Train Test Split
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(

    images,

    labels_encoded,

    test_size=0.20,

    random_state=42,

    stratify=np.argmax(labels_encoded, axis=1),

    shuffle=True

)

print("Training :", X_train.shape)

print("Testing  :", X_test.shape)

# ==========================================================
# Data Augmentation
# ==========================================================

train_datagen = ImageDataGenerator(

    rotation_range=20,

    width_shift_range=0.2,

    height_shift_range=0.2,

    zoom_range=0.2,

    shear_range=0.2,

    horizontal_flip=True,

    fill_mode="nearest"

)

test_datagen = ImageDataGenerator()

# ==========================================================
# Data Generators
# ==========================================================

train_generator = train_datagen.flow(

    X_train,

    y_train,

    batch_size=BATCH_SIZE,

    shuffle=True

)

test_generator = test_datagen.flow(

    X_test,

    y_test,

    batch_size=BATCH_SIZE,

    shuffle=False

)

print("Training Batches :", len(train_generator))

print("Testing Batches  :", len(test_generator))

# ==========================================================
# Class Distribution
# ==========================================================

print("Training Distribution\n")

train_labels = np.argmax(y_train, axis=1)

for i, cls in enumerate(encoder.classes_):

    print(cls, ":", np.sum(train_labels == i))

print("\nTesting Distribution\n")

test_labels = np.argmax(y_test, axis=1)

for i, cls in enumerate(encoder.classes_):

    print(cls, ":", np.sum(test_labels == i))

# ==========================================================
# ConViTX Hyperparameters
# ==========================================================

image_size = 224

patch_size = 7

num_patches = (image_size // patch_size) ** 2

projection_dim = 48

num_heads = 4

transformer_layers = 8

transformer_units = [

    projection_dim * 2,

    projection_dim

]

print("Number of patches :", num_patches)

# ==========================================================
# MobileNetV2 Backbone
# ==========================================================

base_model = tf.keras.applications.MobileNetV2(

    input_shape=(224,224,3),

    include_top=False,

    weights="imagenet"

)

base_model.trainable = True

print("Backbone Loaded")

base_model.summary()

# ==========================================================
# MLP Block
# ==========================================================

def mlp(x, hidden_units, dropout_rate):

    for units in hidden_units:

        x = layers.Dense(
            units,
            activation=tf.nn.gelu
        )(x)

        x = layers.Dropout(
            dropout_rate
        )(x)

    return x

# ==========================================================
# Patch Layer
# ==========================================================

class Patches(layers.Layer):

    def __init__(self, patch_size, **kwargs):

        super().__init__(**kwargs)

        self.patch_size = patch_size

    def call(self, images):

        batch_size = tf.shape(images)[0]

        patches = tf.image.extract_patches(

            images=images,

            sizes=[1,self.patch_size,self.patch_size,1],

            strides=[1,self.patch_size,self.patch_size,1],

            rates=[1,1,1,1],

            padding="VALID"

        )

        patch_dim = patches.shape[-1]

        patches = tf.reshape(

            patches,

            [batch_size,-1,patch_dim]

        )

        return patches

    def get_config(self):

        config = super().get_config()

        config.update({

            "patch_size":self.patch_size

        })

        return config

# ==========================================================
# Patch Encoder
# ==========================================================

class PatchEncoder(layers.Layer):

    def __init__(self,
                 num_patches,
                 projection_dim,
                 **kwargs):

        super().__init__(**kwargs)

        self.num_patches = num_patches

        self.projection_dim = projection_dim

        self.projection = layers.Dense(

            projection_dim

        )

        self.position_embedding = layers.Embedding(

            input_dim=num_patches,

            output_dim=projection_dim

        )

    def call(self, patches):

        positions = tf.range(

            start=0,

            limit=self.num_patches,

            delta=1

        )

        encoded = self.projection(

            patches

        ) + self.position_embedding(

            positions

        )

        return encoded

    def get_config(self):

        config = super().get_config()

        config.update({

            "num_patches":self.num_patches,

            "projection_dim":self.projection_dim

        })

        return config

# ==========================================================
# SE Block
# ==========================================================

def se_block(inputs, ratio=4):

    channels = inputs.shape[-1]

    x = layers.GlobalAveragePooling2D()(inputs)

    x = layers.Reshape((1,1,channels))(x)

    x = layers.Dense(

        channels//ratio,

        activation="relu",

        kernel_initializer="he_normal"

    )(x)

    x = layers.Dense(

        channels,

        activation="sigmoid",

        kernel_initializer="he_normal"

    )(x)

    return layers.Multiply()([inputs,x])

# ==========================================================
# CNN Feature Extraction
# ==========================================================

cnn_layers = base_model.get_layer(

    "block_6_project_BN"

).output

cnn_features = se_block(

    cnn_layers,

    ratio=4

)

print(cnn_features.shape)

# ==========================================================
# Patch Creation Test
# ==========================================================

patches = Patches(

    patch_size

)(base_model.input)

print(patches.shape)

# ==========================================================
# Patch Encoding Test
# ==========================================================

encoded_patches = PatchEncoder(

    num_patches,

    projection_dim

)(patches)

print(encoded_patches.shape)

# ==========================================================
# Vision Transformer Encoder
# ==========================================================

encoded = encoded_patches

for i in range(transformer_layers):

    x1 = layers.LayerNormalization(
        epsilon=1e-6,
        name=f"LN1_{i}"
    )(encoded)

    attention = layers.MultiHeadAttention(
        num_heads=num_heads,
        key_dim=projection_dim,
        dropout=0.1,
        name=f"MHA_{i}"
    )(x1, x1)

    x2 = layers.Add()([attention, encoded])

    x3 = layers.LayerNormalization(
        epsilon=1e-6,
        name=f"LN2_{i}"
    )(x2)

    x3 = mlp(
        x3,
        hidden_units=transformer_units,
        dropout_rate=0.1
    )

    encoded = layers.Add()([x3, x2])

vit_output = layers.LayerNormalization(
    epsilon=1e-6
)(encoded)

print(vit_output.shape)

# ==========================================================
# Convert Tokens -> Feature Map
# ==========================================================

grid_size = image_size // patch_size

vit_features = layers.Reshape(

    (grid_size,
     grid_size,
     projection_dim)

)(vit_output)

print(vit_features.shape)

# ==========================================================
# ViT Feature Refinement
# ==========================================================

vit_features = layers.DepthwiseConv2D(
    3,
    padding="same",
    activation="relu"
)(vit_features)

vit_features = layers.DepthwiseConv2D(
    3,
    padding="same",
    activation="relu"
)(vit_features)

vit_features = layers.DepthwiseConv2D(
    3,
    strides=2,
    padding="same",
    activation="relu"
)(vit_features)

vit_features = layers.DepthwiseConv2D(
    3,
    strides=2,
    padding="same",
    activation="relu"
)(vit_features)

vit_features = se_block(vit_features)

print(vit_features.shape)

# ==========================================================
# Resize CNN Features
# ==========================================================

cnn_features = layers.MaxPooling2D(
    pool_size=2
)(cnn_features)

print(cnn_features.shape)

# ==========================================================
# Resize ViT Features
# ==========================================================

vit_features = layers.Resizing(
    7,
    7
)(vit_features)

print(vit_features.shape)

# ==========================================================
# Feature Fusion
# ==========================================================

fusion = layers.Concatenate(
    axis=-1,
    name="cam_layer1"
)([cnn_features, vit_features])

print(fusion.shape)

# ==========================================================
# Fusion Block
# ==========================================================

fusion = layers.Conv2D(

    128,

    3,

    padding="same",

    activation="relu"

)(fusion)

fusion = layers.BatchNormalization()(fusion)

fusion = se_block(fusion)

print(fusion.shape)

# ==========================================================
# Classification Head
# ==========================================================

gap_layer = layers.GlobalAveragePooling2D()(fusion)

dropout = layers.Dropout(0.3)(gap_layer)

output = layers.Dense(

    NUM_CLASSES,

    activation="softmax",

    name="Predictions"

)(dropout)

# ==========================================================
# Build Model
# ==========================================================

model = tf.keras.Model(

    inputs=base_model.input,

    outputs=output,

    name="ConViTX"

)

model.summary()

print("Input Shape :", model.input_shape)

print("Output Shape:", model.output_shape)

# ==========================================================
# Optimizer
# ==========================================================

optimizer = tf.keras.optimizers.Adam(
    learning_rate=1e-4
)

model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.CategoricalCrossentropy(
        label_smoothing=0.1
    ),
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint,
    LearningRateScheduler
)

# Step decay schedule
def lr_scheduler(epoch, lr):

    if epoch < 20:
        return 1e-4

    elif epoch < 50:
        return 5e-5

    elif epoch < 80:
        return 2e-5

    elif epoch < 100:
        return 1e-5

    else:
        return 5e-6


lr_callback = LearningRateScheduler(
    lr_scheduler,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=5,
    verbose=1,
    min_lr=1e-7
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True,
    verbose=1
)

checkpoint = ModelCheckpoint(
    "Best_ConViTX.keras",
    monitor="val_accuracy",
    save_best_only=True,
    mode="max",
    verbose=1
)

history = model.fit(

    train_generator,

    validation_data=test_generator,

    epochs=120,

    callbacks=[
        lr_callback,
        reduce_lr,
        early_stop,
        checkpoint
    ],

    verbose=1
)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.plot(history.history["accuracy"], label="Train Accuracy")

plt.plot(history.history["val_accuracy"], label="Validation Accuracy")

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(12,5))

plt.plot(history.history["loss"], label="Train Loss")

plt.plot(history.history["val_loss"], label="Validation Loss")

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.grid(True)

plt.show()

# ==========================================================
# Evaluation Libraries
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ==========================================================
# Predict on Test Set (Corrected)
# ==========================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Predict probabilities
pred_prob = model.predict(
    X_test,
    batch_size=32,
    verbose=1
)

# Predicted class indices
y_pred = np.argmax(pred_prob, axis=1)

# True class indices
y_true = np.argmax(y_test, axis=1)

print("Prediction Shape :", pred_prob.shape)

# ==========================================================
# Metrics
# ==========================================================

accuracy = accuracy_score(y_true, y_pred)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted"
)

print("\n==============================")
print("Evaluation Results")
print("==============================")

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

# ==========================================================
# Classification Report
# ==========================================================

print("\nClassification Report\n")

print(
    classification_report(
        y_true,
        y_pred,
        target_names=encoder.classes_,
        digits=4
    )
)

# ==========================================================
# Confusion Matrix
# ==========================================================

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(7,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=encoder.classes_,
    yticklabels=encoder.classes_
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

# ==========================================================
# ROC, AUC, Precision-Recall, mAP
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score
)

# ==========================================================
# Predict Probabilities
# ==========================================================

pred_prob = model.predict(
    X_test,
    batch_size=32,
    verbose=1
)

y_true = np.argmax(y_test, axis=1)

y_pred = np.argmax(pred_prob, axis=1)

print(pred_prob.shape)

# ==========================================================
# One Hot Labels
# ==========================================================

num_classes = len(encoder.classes_)

y_test_onehot = y_test

print(y_test_onehot.shape)

# ==========================================================
# ROC Curve
# ==========================================================

plt.figure(figsize=(8,8))

roc_auc = {}

for i in range(num_classes):

    fpr, tpr, _ = roc_curve(

        y_test_onehot[:, i],

        pred_prob[:, i]

    )

    roc_auc[i] = auc(fpr, tpr)

    plt.plot(

        fpr,

        tpr,

        lw=2,

        label=f"{encoder.classes_[i]} (AUC={roc_auc[i]:.3f})"

    )

plt.plot([0,1],[0,1],'k--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.grid(True)

plt.show()

# ==========================================================
# Precision Recall Curve
# ==========================================================

plt.figure(figsize=(8,8))

average_precision = {}

for i in range(num_classes):

    precision, recall, _ = precision_recall_curve(

        y_test_onehot[:,i],

        pred_prob[:,i]

    )

    average_precision[i] = average_precision_score(

        y_test_onehot[:,i],

        pred_prob[:,i]

    )

    plt.plot(

        recall,

        precision,

        lw=2,

        label=f"{encoder.classes_[i]} (AP={average_precision[i]:.3f})"

    )

plt.xlabel("Recall")

plt.ylabel("Precision")

plt.title("Precision-Recall Curve")

plt.legend()

plt.grid(True)

plt.show()

# ==========================================================
# Mean Average Precision
# ==========================================================

mAP = np.mean(

    list(average_precision.values())

)

print("Mean Average Precision (mAP): {:.4f}".format(mAP))

# ==========================================================
# Individual AUC
# ==========================================================

print("\nAUC Scores\n")

for i in range(num_classes):

    print(

        encoder.classes_[i],

        ":",

        round(roc_auc[i],4)

    )

# ==========================================================
# Save Metrics
# ==========================================================

metrics = {

    "Accuracy": accuracy,

    "Precision": precision_score(

        y_true,

        y_pred,

        average="weighted"

    ),

    "Recall": recall_score(

        y_true,

        y_pred,

        average="weighted"

    ),

    "F1": f1_score(

        y_true,

        y_pred,

        average="weighted"

    ),

    "mAP": mAP

}

for k, v in metrics.items():

    print(f"{k:12s}: {v:.4f}")

# ==========================================================
# Save Results
# ==========================================================

import pandas as pd

df = pd.DataFrame({

    "Metric":[

        "Accuracy",

        "Precision",

        "Recall",

        "F1 Score",

        "mAP"

    ],

    "Value":[

        metrics["Accuracy"],

        metrics["Precision"],

        metrics["Recall"],

        metrics["F1"],

        metrics["mAP"]

    ]

})

df.to_csv(

    "ConViTX_Metrics.csv",

    index=False

)

print(df)

print("\nSaved as ConViTX_Metrics.csv")

# ==========================================================
# Grad-CAM Imports
# ==========================================================

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2

# ==========================================================
# Check Layer Name
# ==========================================================

for layer in model.layers:

    print(layer.name)

# ==========================================================
# GradCAM Model
# ==========================================================

last_conv_layer_name = "cam_layer1"

grad_model = tf.keras.models.Model(

    inputs=model.inputs,

    outputs=[
        model.get_layer(last_conv_layer_name).output,
        model.output
    ]

)

print("GradCAM model ready.")

# ==========================================================
# GradCAM Function
# ==========================================================

def make_gradcam_heatmap(img_array,
                         grad_model,
                         pred_index=None):

    with tf.GradientTape() as tape:

        conv_outputs, predictions = grad_model(img_array)

        if pred_index is None:

            pred_index = tf.argmax(predictions[0])

        class_channel = predictions[:, pred_index]

    grads = tape.gradient(

        class_channel,

        conv_outputs

    )

    pooled_grads = tf.reduce_mean(

        grads,

        axis=(0,1,2)

    )

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]

    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap,0)

    heatmap /= (

        tf.reduce_max(heatmap) + 1e-8

    )

    return heatmap.numpy()

# ==========================================================
# Choose Image
# ==========================================================

index = np.random.randint(len(X_test))

img = X_test[index]

img_input = np.expand_dims(img, axis=0)

prediction = model.predict(img_input)

predicted = np.argmax(prediction)

actual = np.argmax(y_test[index])

print("Predicted :", encoder.classes_[predicted])

print("Actual    :", encoder.classes_[actual])

# ==========================================================
# Generate Heatmap
# ==========================================================

heatmap = make_gradcam_heatmap(

    img_input,

    grad_model

)

plt.imshow(heatmap,cmap="jet")

plt.colorbar()

plt.title("GradCAM Heatmap")

plt.axis("off")

plt.show()

# ==========================================================
# Overlay Heatmap
# ==========================================================

display_img = ((img + 1.0)/2.0)

display_img = np.clip(display_img,0,1)

heatmap = cv2.resize(

    heatmap,

    (224,224)

)

heatmap = np.uint8(

    255*heatmap

)

heatmap = cv2.applyColorMap(

    heatmap,

    cv2.COLORMAP_JET

)

overlay = cv2.addWeighted(

    np.uint8(display_img*255),

    0.6,

    heatmap,

    0.4,

    0

)

plt.figure(figsize=(12,4))

plt.subplot(131)

plt.imshow(display_img)

plt.title("Input")

plt.axis("off")

plt.subplot(132)

plt.imshow(cv2.cvtColor(heatmap,cv2.COLOR_BGR2RGB))

plt.title("Heatmap")

plt.axis("off")

plt.subplot(133)

plt.imshow(cv2.cvtColor(overlay,cv2.COLOR_BGR2RGB))

plt.title("GradCAM")

plt.axis("off")

plt.show()

# ==========================================================
# Save GradCAM
# ==========================================================

cv2.imwrite(

    "GradCAM_Result.png",

    overlay

)

print("Saved GradCAM_Result.png")