# -*- coding: utf-8 -*-
"""ConViTX_Potato_PlantVillage_Colab_Template (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlWfxkBG8V2NYFo0RqM6SZc6AZGGk5yN

# ConViTX on Potato PlantVillage
Pipeline:
1. Load Potato dataset
2. Leaf segmentation
3. Train/test split (80:20)
4. ConViTX model (paste your architecture)
5. Train
6. Evaluate (Accuracy, Precision, Recall, F1, mAP)
7. Grad-CAM
8. LIME
9. t-SNE
"""

# ==========================================================
# ConViTX for Potato PlantVillage Dataset
# Part 1/20 : Dataset Preparation
# ==========================================================

# Install required libraries
!pip install -q lime tensorflow opencv-python scikit-learn matplotlib seaborn

import os
import cv2
import zipfile
import random
import warnings
import numpy as np
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

import tensorflow as tf

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

print("TensorFlow Version:", tf.__version__)

# ==========================================================
# Extract Potato.zip
# ==========================================================

zip_path = "/content/Potato.zip"
extract_path = "/content/Potato_dataset"

if not os.path.exists(extract_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)

print("Dataset Extracted Successfully!")

# ==========================================================
# Leaf Segmentation
# ==========================================================

def segment_leaf(image):

    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

    lower_green = np.array([25,40,40])
    upper_green = np.array([90,255,255])

    mask = cv2.inRange(hsv, lower_green, upper_green)

    kernel = np.ones((5,5),np.uint8)

    mask = cv2.morphologyEx(mask,
                            cv2.MORPH_OPEN,
                            kernel)

    segmented = cv2.bitwise_and(image,
                                image,
                                mask=mask)

    return segmented

# ==========================================================
# Verify Dataset Structure
# ==========================================================

for root, dirs, files in os.walk(extract_path):
    print(root, " -> ", len(files))

# ==========================================================
# Load Potato Dataset Directly from ZIP (No Extraction)
# ==========================================================

import zipfile
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

ZIP_PATH = "/content/Potato.zip"
IMG_SIZE = 224

images = []
labels = []

with zipfile.ZipFile(ZIP_PATH, "r") as zip_file:

    image_files = [

        f for f in zip_file.namelist()

        if f.lower().endswith((".jpg", ".jpeg", ".png"))

    ]

    print("Total Images Found :", len(image_files))

    for file in image_files:

        parts = file.split("/")

        if len(parts) < 2:
            continue

        label = parts[-2]

        image_bytes = zip_file.read(file)

        image_array = np.frombuffer(image_bytes, np.uint8)

        img = cv2.imdecode(image_array, cv2.IMREAD_COLOR)

        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Leaf Segmentation
        img = segment_leaf(img)

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        images.append(img)

        labels.append(label)

images = np.array(images, dtype=np.float32) / 255.0
labels = np.array(labels)

print("Images Shape :", images.shape)
print("Labels Shape :", labels.shape)

# ==========================================================
# Encode Labels
# ==========================================================

encoder = LabelEncoder()

labels = encoder.fit_transform(labels)

print("Classes :", encoder.classes_)

num_classes = len(encoder.classes_)

labels = to_categorical(labels, num_classes)

print("Total Classes :", num_classes)

# ==========================================================
# Train Test Split
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(

    images,

    labels,

    test_size=0.20,

    random_state=42,

    stratify=np.argmax(labels, axis=1)

)

print()

print("Training Images :", X_train.shape)

print("Testing Images  :", X_test.shape)

# ==========================================================
# Visualize Samples
# ==========================================================

plt.figure(figsize=(12,8))

for i in range(9):

    index = random.randint(0, len(images)-1)

    plt.subplot(3,3,i+1)

    plt.imshow(images[index])

    plt.title(encoder.classes_[np.argmax(labels[index])])

    plt.axis("off")

plt.tight_layout()

plt.show()

images = np.array(images,dtype=np.float32)/255.0

labels = np.array(labels)

print(images.shape)

print(labels.shape)

# ==========================================================
# Required Imports
# ==========================================================

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import backend as K

# ==========================================================
# MLP Block
# ==========================================================

def mlp(x, hidden_units, dropout_rate):

    for units in hidden_units:

        x = layers.Dense(
            units,
            activation=tf.nn.gelu
        )(x)

        x = layers.Dropout(
            dropout_rate
        )(x)

    return x

# ==========================================================
# Patch Layer
# ==========================================================

class Patches(layers.Layer):

    def __init__(self, patch_size, **kwargs):

        super(Patches, self).__init__()

        self.patch_size = patch_size

    def get_config(self):

        config = super().get_config()

        config.update({
            "patch_size": self.patch_size
        })

        return config

    def call(self, images):

        batch_size = tf.shape(images)[0]

        patches = tf.image.extract_patches(

            images=images,

            sizes=[1,self.patch_size,self.patch_size,1],

            strides=[1,self.patch_size,self.patch_size,1],

            rates=[1,1,1,1],

            padding="VALID"

        )

        patch_dims = patches.shape[-1]

        patches = tf.reshape(

            patches,

            [batch_size,-1,patch_dims]

        )

        return patches

# ==========================================================
# Hyperparameters
# ==========================================================

image_size = 224

patch_size = 7

num_patches = (image_size // patch_size) ** 2

projection_dim = 48

num_heads = 4

transformer_units = [

    projection_dim * 2,

    projection_dim

]

transformer_layers = 8

dropout_rate = 0.1

print("Number of Patches :", num_patches)

# ==========================================================
# MobileNetV2 Backbone
# ==========================================================

base_model = tf.keras.applications.MobileNetV2(

    input_shape=(224,224,3),

    include_top=False,

    weights="imagenet"

)

base_model.trainable = True

base_model.summary()

# ==========================================================
# Squeeze-and-Excitation Block
# ==========================================================

def se_block(input_feature, ratio=4):

    channel_axis = 1 if K.image_data_format()=="channels_first" else -1

    channel = input_feature.shape[channel_axis]

    se_feature = layers.GlobalAveragePooling2D()(input_feature)

    se_feature = layers.Reshape(

        (1,1,channel)

    )(se_feature)

    se_feature = layers.Dense(

        channel // ratio,

        activation="relu",

        kernel_initializer="he_normal",

        use_bias=True,

        bias_initializer="zeros"

    )(se_feature)

    se_feature = layers.Dense(

        channel,

        activation="sigmoid",

        kernel_initializer="he_normal",

        use_bias=True,

        bias_initializer="zeros"

    )(se_feature)

    if K.image_data_format()=="channels_first":

        se_feature = layers.Permute(

            (3,1,2)

        )(se_feature)

    se_feature = layers.multiply(

        [input_feature,se_feature]

    )

    return se_feature

# ==========================================================
# CNN Branch
# ==========================================================

cnn_layers = base_model.get_layer(

    "block_6_project_BN"

).output

cnn_features = se_block(

    cnn_layers,

    ratio=4

)

print(cnn_features.shape)

from tensorflow.keras import layers
import tensorflow as tf

class PatchEncoder(layers.Layer):

    def __init__(self, num_patches, projection_dim, **kwargs):
        super(PatchEncoder, self).__init__(**kwargs)

        self.num_patches = num_patches
        self.projection_dim = projection_dim

        self.projection = layers.Dense(units=projection_dim)

        self.position_embedding = layers.Embedding(
            input_dim=num_patches,
            output_dim=projection_dim
        )

    def call(self, patch):

        positions = tf.range(
            start=0,
            limit=self.num_patches,
            delta=1
        )

        encoded = self.projection(patch) + self.position_embedding(positions)

        return encoded

    def get_config(self):
        config = super().get_config()
        config.update({
            "num_patches": self.num_patches,
            "projection_dim": self.projection_dim
        })
        return config
        patches = Patches(patch_size)(base_model.input)

encoded_patches = PatchEncoder(
    num_patches,
    projection_dim
)(patches)

print(encoded_patches.shape)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Data Augmentation for Training
train_datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True,
    fill_mode="nearest"
)

# Only rescaling for testing
test_datagen = ImageDataGenerator()

train_generator = train_datagen.flow(
    X_train,
    y_train,
    batch_size=32,
    shuffle=True
)

test_generator = test_datagen.flow(
    X_test,
    y_test,
    batch_size=32,
    shuffle=False
)

# ==========================================================
# Vision Transformer Branch
# ==========================================================

# Create patches
patches = Patches(patch_size)(base_model.input)

print("Patch Shape :", patches.shape)

# Encode patches
encoded_patches = PatchEncoder(
    num_patches=num_patches,
    projection_dim=projection_dim
)(patches)

print("Encoded Shape :", encoded_patches.shape)

# ==========================================================
# Transformer Encoder
# ==========================================================

for i in range(transformer_layers):

    # Layer Normalization
    x1 = layers.LayerNormalization(
        epsilon=1e-6,
        name=f"LayerNorm1_{i}"
    )(encoded_patches)

    # Multi Head Self Attention
    attention_output = layers.MultiHeadAttention(

        num_heads=num_heads,

        key_dim=projection_dim,

        dropout=0.1,

        name=f"MHSA_{i}"

    )(x1, x1)

    # Skip Connection
    x2 = layers.Add(
        name=f"Skip1_{i}"
    )([attention_output, encoded_patches])

    # Layer Normalization
    x3 = layers.LayerNormalization(
        epsilon=1e-6,
        name=f"LayerNorm2_{i}"
    )(x2)

    # Feed Forward Network
    x3 = mlp(
        x3,
        hidden_units=transformer_units,
        dropout_rate=0.1
    )

    # Skip Connection
    encoded_patches = layers.Add(
        name=f"Skip2_{i}"
    )([x3, x2])

print(encoded_patches.shape)

# ==========================================================
# Final ViT Features
# ==========================================================

vit_layers = layers.LayerNormalization(
    epsilon=1e-6
)(encoded_patches)

print(vit_layers.shape)

# ==========================================================
# Reshape Tokens
# ==========================================================

vit_features = layers.Reshape(
    (32,32,48)
)(vit_layers)

print(vit_features.shape)

vit_features = layers.DepthwiseConv2D(

    kernel_size=3,

    strides=1,

    padding="valid",

    activation="relu",

    use_bias=True

)(vit_features)

print(vit_features.shape)

vit_features = layers.DepthwiseConv2D(

    kernel_size=3,

    strides=1,

    padding="valid",

    activation="relu",

    use_bias=True

)(vit_features)

print(vit_features.shape)

vit_features = layers.DepthwiseConv2D(

    kernel_size=3,

    strides=2,

    padding="same",

    activation="relu",

    use_bias=True

)(vit_features)

print(vit_features.shape)

# ==========================================================
# SE Attention
# ==========================================================

vit_features = se_block(
    vit_features,
    ratio=4
)

print(vit_features.shape)

print(cnn_features.shape)

# ==========================================================
# Feature Fusion
# ==========================================================

print("CNN Feature Shape :", cnn_features.shape)
print("ViT Feature Shape :", vit_features.shape)

feature_fusion = layers.Concatenate(
    axis=-1,
    name="cam_layer1"
)([cnn_features, vit_features])

print("Fusion Shape :", feature_fusion.shape)

# ==========================================================
# Make Divisible
# ==========================================================

def _make_divisible(v, divisor=8, min_value=None):

    if min_value is None:
        min_value = divisor

    new_v = max(
        min_value,
        int(v + divisor / 2) // divisor * divisor
    )

    if new_v < 0.9 * v:
        new_v += divisor

    return new_v

# ==========================================================
# Inverted Residual Block
# ==========================================================

def _inverted_res_block(inputs,
                        expansion,
                        stride,
                        alpha,
                        filters,
                        block_id):

    channel_axis = -1

    in_channels = K.int_shape(inputs)[channel_axis]

    pointwise_conv_filters = int(filters * alpha)

    pointwise_filters = _make_divisible(
        pointwise_conv_filters,
        8
    )

    x = inputs

    prefix = f"block_{block_id}_"

    # Expansion
    x = layers.Conv2D(
        expansion * in_channels,
        kernel_size=1,
        padding="same",
        use_bias=False,
        name=prefix+"expand"
    )(x)

    x = layers.BatchNormalization(
        name=prefix+"expand_BN"
    )(x)

    x = layers.ReLU(6.)(x)

    # Depthwise
    x = layers.DepthwiseConv2D(
        kernel_size=3,
        strides=stride,
        padding="same",
        use_bias=False,
        name=prefix+"depthwise"
    )(x)

    x = layers.BatchNormalization(
        name=prefix+"depthwise_BN"
    )(x)

    x = layers.ReLU(6.)(x)

    # Projection
    x = layers.Conv2D(
        pointwise_filters,
        kernel_size=1,
        padding="same",
        use_bias=False,
        name=prefix+"project"
    )(x)

    x = layers.BatchNormalization(
        name=prefix+"project_BN"
    )(x)

    return x

# ==========================================================
# Fusion Block
# ==========================================================

feature_fusion = _inverted_res_block(

    feature_fusion,

    expansion=6,

    stride=2,

    alpha=1.0,

    filters=128,

    block_id=12

)

print(feature_fusion.shape)

# ==========================================================
# SE Attention
# ==========================================================

feature_fusion = se_block(

    feature_fusion,

    ratio=4

)

print(feature_fusion.shape)

# ==========================================================
# GAP
# ==========================================================

gap_layer = layers.GlobalAveragePooling2D()(feature_fusion)

print(gap_layer.shape)

# ==========================================================
# Output Layer
# ==========================================================

predictions = layers.Dense(

    3,

    activation="softmax",

    name="Predictions"

)(gap_layer)

# ==========================================================
# Build ConViTX Model
# ==========================================================

model = tf.keras.Model(

    inputs=base_model.input,

    outputs=predictions,

    name="ConViTX"

)

model.summary()

print(model.output_shape)

tf.keras.utils.plot_model(

    model,

    show_shapes=True,

    dpi=120

)

# ==========================================================
# Import Libraries
# ==========================================================

import tensorflow as tf

from tensorflow.keras.optimizers import Adam

from tensorflow.keras.callbacks import (

    EarlyStopping,

    ReduceLROnPlateau,

    ModelCheckpoint

)

import matplotlib.pyplot as plt

# ==========================================================
# Compile Model
# ==========================================================

model.compile(

    optimizer=Adam(

        learning_rate=0.0001

    ),

    loss="categorical_crossentropy",

    metrics=["accuracy"]

)

print("Model Compiled Successfully")

# ==========================================================
# Callbacks
# ==========================================================

checkpoint = ModelCheckpoint(

    "ConViTX_Best_Model.keras",

    monitor="val_accuracy",

    save_best_only=True,

    mode="max",

    verbose=1

)

earlystop = EarlyStopping(

    monitor="val_loss",

    patience=8,

    restore_best_weights=True,

    verbose=1

)

reduce_lr = ReduceLROnPlateau(

    monitor="val_loss",

    factor=0.2,

    patience=4,

    min_lr=1e-7,

    verbose=1

)

callbacks = [

    checkpoint,

    earlystop,

    reduce_lr

]

history = model.fit(

    train_generator,

    validation_data=test_generator,

    epochs=30,

    callbacks=callbacks,

    verbose=1

)

model.save(

    "ConViTX_Final.keras"

)

print("Model Saved")

plt.figure(figsize=(8,5))

plt.plot(

    history.history["accuracy"],

    label="Training Accuracy"

)

plt.plot(

    history.history["val_accuracy"],

    label="Validation Accuracy"

)

plt.xlabel("Epoch")

plt.ylabel("Accuracy")

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(

    history.history["loss"],

    label="Training Loss"

)

plt.plot(

    history.history["val_loss"],

    label="Validation Loss"

)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.legend()

plt.grid(True)

plt.show()

best_acc = max(history.history["val_accuracy"])

print("Best Validation Accuracy :", best_acc)

# ==========================================================
# Evaluation Libraries
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (

    accuracy_score,

    precision_score,

    recall_score,

    f1_score,

    classification_report,

    confusion_matrix,

    roc_curve,

    auc,

    average_precision_score

)

from sklearn.preprocessing import label_binarize

# ==========================================================
# Prediction
# ==========================================================

y_prob = model.predict(X_test)

y_pred = np.argmax(y_prob, axis=1)

y_true = np.argmax(y_test, axis=1)

print("Prediction Completed")

# ==========================================================
# Accuracy
# ==========================================================

accuracy = accuracy_score(y_true, y_pred)

print("Accuracy : {:.4f}".format(accuracy))

# ==========================================================
# Precision
# ==========================================================

precision = precision_score(

    y_true,

    y_pred,

    average="weighted"

)

print("Precision : {:.4f}".format(precision))

# ==========================================================
# Recall
# ==========================================================

recall = recall_score(

    y_true,

    y_pred,

    average="weighted"

)

print("Recall : {:.4f}".format(recall))

# ==========================================================
# F1 Score
# ==========================================================

f1 = f1_score(

    y_true,

    y_pred,

    average="weighted"

)

print("F1 Score : {:.4f}".format(f1))

# ==========================================================
# Classification Report
# ==========================================================

print(

classification_report(

    y_true,

    y_pred,

    target_names=encoder.classes_

)

)

# ==========================================================
# Confusion Matrix
# ==========================================================

cm = confusion_matrix(

    y_true,

    y_pred

)

plt.figure(figsize=(6,5))

sns.heatmap(

    cm,

    annot=True,

    cmap="Blues",

    fmt="d",

    xticklabels=encoder.classes_,

    yticklabels=encoder.classes_

)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

# ==========================================================
# ROC Curve
# ==========================================================

classes = len(encoder.classes_)

y_test_bin = label_binarize(

    y_true,

    classes=np.arange(classes)

)

plt.figure(figsize=(8,6))

for i in range(classes):

    fpr, tpr, _ = roc_curve(

        y_test_bin[:, i],

        y_prob[:, i]

    )

    roc_auc = auc(fpr, tpr)

    plt.plot(

        fpr,

        tpr,

        label=f"{encoder.classes_[i]} (AUC={roc_auc:.3f})"

    )

plt.plot([0,1],[0,1],'k--')

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.grid(True)

plt.show()

# ==========================================================
# Multi-class AUC
# ==========================================================

overall_auc = auc(
    *roc_curve(
        y_test_bin.ravel(),
        y_prob.ravel()
    )[:2]
)

print("Overall AUC :", overall_auc)

# ==========================================================
# Mean Average Precision
# ==========================================================

map_score = average_precision_score(

    y_test,

    y_prob,

    average="macro"

)

print("mAP :", map_score)

# ==========================================================
# Final Results
# ==========================================================

print("="*45)

print("Accuracy  :", accuracy)

print("Precision :", precision)

print("Recall    :", recall)

print("F1 Score  :", f1)

print("AUC       :", overall_auc)

print("mAP       :", map_score)

print("="*45)

# ==========================================================
# Grad-CAM Libraries
# ==========================================================

import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

# ==========================================================
# Grad-CAM Function
# ==========================================================

def make_gradcam_heatmap(img_array, model, last_conv_layer_name):

    grad_model = tf.keras.models.Model(
        inputs=model.inputs,
        outputs=[
            model.get_layer(last_conv_layer_name).output,
            model.output
        ]
    )

    with tf.GradientTape() as tape:

        conv_outputs, predictions = grad_model(img_array)

        pred_index = tf.argmax(predictions[0])

        class_channel = predictions[:, pred_index]

    grads = tape.gradient(class_channel, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]

    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap,0)

    heatmap /= tf.reduce_max(heatmap) + 1e-8

    return heatmap.numpy()

# ==========================================================
# Overlay Heatmap
# ==========================================================

def overlay_heatmap(heatmap, image, alpha=0.4):

    heatmap = cv2.resize(

        heatmap,

        (image.shape[1], image.shape[0])

    )

    heatmap = np.uint8(255*heatmap)

    heatmap = cv2.applyColorMap(

        heatmap,

        cv2.COLORMAP_JET

    )

    overlay = cv2.addWeighted(

        image,

        1-alpha,

        heatmap,

        alpha,

        0

    )

    return overlay

# ==========================================================
# Test One Image
# ==========================================================

index = 10

img = X_test[index]

img_input = np.expand_dims(img, axis=0)

heatmap = make_gradcam_heatmap(

    img_input,

    model,

    "cam_layer1"

)

overlay = overlay_heatmap(

    heatmap,

    np.uint8(img*255)

)

# ==========================================================
# Display
# ==========================================================

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)

plt.imshow(img)

plt.title("Original")

plt.axis("off")

plt.subplot(1,3,2)

plt.imshow(heatmap,cmap="jet")

plt.title("Grad-CAM")

plt.axis("off")

plt.subplot(1,3,3)

plt.imshow(overlay)

plt.title("Overlay")

plt.axis("off")

plt.show()

# ==========================================================
# Prediction
# ==========================================================

prediction = model.predict(img_input)

pred = np.argmax(prediction)

true = np.argmax(y_test[index])

print("Predicted :", encoder.classes_[pred])

print("Actual :", encoder.classes_[true])

print("Confidence :", np.max(prediction))

# ==========================================================
# Show 6 Grad-CAM Results
# ==========================================================

plt.figure(figsize=(18,12))

for i in range(6):

    idx = np.random.randint(0, len(X_test))

    img = X_test[idx]

    img_input = np.expand_dims(img,0)

    heatmap = make_gradcam_heatmap(

        img_input,

        model,

        "cam_layer1"

    )

    overlay = overlay_heatmap(

        heatmap,

        np.uint8(img*255)

    )

    plt.subplot(2,3,i+1)

    plt.imshow(overlay)

    pred = np.argmax(model.predict(img_input,verbose=0))

    plt.title(

        encoder.classes_[pred]

    )

    plt.axis("off")

plt.tight_layout()

plt.show()

cv2.imwrite(

    "GradCAM_Result.png",

    cv2.cvtColor(

        overlay,

        cv2.COLOR_RGB2BGR

    )

)

print("GradCAM saved.")

# ==========================================================
# Install LIME
# ==========================================================

!pip install -q lime

# ==========================================================
# Imports
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt

from lime import lime_image

from skimage.segmentation import mark_boundaries

# ==========================================================
# Prediction Function
# ==========================================================

def predict_fn(images):

    images = np.array(images, dtype=np.float32)

    return model.predict(images, verbose=0)

# ==========================================================
# LIME Explainer
# ==========================================================

explainer = lime_image.LimeImageExplainer()

# ==========================================================
# Test Image
# ==========================================================

index = np.random.randint(0, len(X_test))

image = X_test[index]

true_label = np.argmax(y_test[index])

print("True Label :", encoder.classes_[true_label])

plt.figure(figsize=(5,5))
plt.imshow(image)
plt.axis("off")
plt.show()

# ==========================================================
# LIME Explanation
# ==========================================================

explanation = explainer.explain_instance(

    image.astype("double"),

    predict_fn,

    top_labels=3,

    hide_color=0,

    num_samples=1000

)

# ==========================================================
# Positive Features
# ==========================================================

temp, mask = explanation.get_image_and_mask(

    explanation.top_labels[0],

    positive_only=True,

    num_features=10,

    hide_rest=False

)

plt.figure(figsize=(6,6))

plt.imshow(

    mark_boundaries(

        temp/255.0,

        mask

    )

)

plt.title("Positive Superpixels")

plt.axis("off")

plt.show()

# ==========================================================
# Positive + Negative
# ==========================================================

temp, mask = explanation.get_image_and_mask(

    explanation.top_labels[0],

    positive_only=False,

    num_features=15,

    hide_rest=False

)

plt.figure(figsize=(6,6))

plt.imshow(

    mark_boundaries(

        temp/255.0,

        mask

    )

)

plt.title("Positive + Negative Regions")

plt.axis("off")

plt.show()

# ==========================================================
# Hide Background
# ==========================================================

temp, mask = explanation.get_image_and_mask(

    explanation.top_labels[0],

    positive_only=True,

    hide_rest=True,

    num_features=8

)

plt.figure(figsize=(6,6))

plt.imshow(temp)

plt.title("Important Regions Only")

plt.axis("off")

plt.show()

# ==========================================================
# Prediction
# ==========================================================

prediction = model.predict(

    np.expand_dims(image,0),

    verbose=0

)

pred = np.argmax(prediction)

print("Predicted :", encoder.classes_[pred])

print("Actual :", encoder.classes_[true_label])

print("Confidence :", np.max(prediction))

# ==========================================================
# Save LIME Image
# ==========================================================

plt.imsave(

    "LIME_Result.png",

    mark_boundaries(temp/255.0, mask)

)

print("LIME image saved.")

# ==========================================================
# Multiple Samples
# ==========================================================

plt.figure(figsize=(15,10))

for i in range(6):

    idx = np.random.randint(0, len(X_test))

    img = X_test[idx]

    exp = explainer.explain_instance(

        img.astype("double"),

        predict_fn,

        top_labels=1,

        num_samples=500

    )

    temp, mask = exp.get_image_and_mask(

        exp.top_labels[0],

        positive_only=True,

        num_features=8,

        hide_rest=False

    )

    plt.subplot(2,3,i+1)

    plt.imshow(

        mark_boundaries(

            temp/255.0,

            mask

        )

    )

    plt.axis("off")

plt.tight_layout()

plt.show()

# ==========================================================
# t-SNE Libraries
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt

from sklearn.manifold import TSNE

# ==========================================================
# Feature Extractor
# ==========================================================

feature_model = tf.keras.Model(

    inputs=model.input,

    outputs=gap_layer

)

print("Feature extractor created.")

# ==========================================================
# Feature Extraction
# ==========================================================

features = feature_model.predict(

    X_test,

    batch_size=32,

    verbose=1

)

print(features.shape)

# ==========================================================
# Labels
# ==========================================================

labels = np.argmax(y_test, axis=1)

print(labels.shape)

# ==========================================================
# t-SNE
# ==========================================================

tsne = TSNE(

    n_components=2,

    perplexity=30,

    learning_rate="auto",

    init="pca",

    random_state=42

)

tsne_features = tsne.fit_transform(features)

print(tsne_features.shape)

# ==========================================================
# Plot
# ==========================================================

plt.figure(figsize=(10,8))

colors = ["red","green","blue"]

for i, cls in enumerate(encoder.classes_):

    idx = labels == i

    plt.scatter(

        tsne_features[idx,0],

        tsne_features[idx,1],

        s=25,

        c=colors[i],

        label=cls,

        alpha=0.7

    )

plt.legend()

plt.title("t-SNE Visualization of ConViTX Features")

plt.xlabel("Dimension 1")

plt.ylabel("Dimension 2")

plt.grid(True)

plt.show()

# ==========================================================
# Save Figure
# ==========================================================

plt.figure(figsize=(10,8))

for i, cls in enumerate(encoder.classes_):

    idx = labels == i

    plt.scatter(

        tsne_features[idx,0],

        tsne_features[idx,1],

        s=25,

        c=colors[i],

        label=cls,

        alpha=0.7

    )

plt.legend()

plt.title("ConViTX t-SNE")

plt.savefig(

    "ConViTX_tSNE.png",

    dpi=300,

    bbox_inches="tight"

)

plt.show()

print("t-SNE figure saved.")

# ==========================================================
# 3D t-SNE
# ==========================================================

from mpl_toolkits.mplot3d import Axes3D

tsne3 = TSNE(

    n_components=3,

    perplexity=30,

    random_state=42,

    learning_rate="auto",

    init="pca"

)

tsne3_features = tsne3.fit_transform(features)

fig = plt.figure(figsize=(10,8))

ax = fig.add_subplot(111, projection='3d')

for i, cls in enumerate(encoder.classes_):

    idx = labels == i

    ax.scatter(

        tsne3_features[idx,0],

        tsne3_features[idx,1],

        tsne3_features[idx,2],

        label=cls,

        s=20

    )

ax.set_title("3D t-SNE of ConViTX Features")

ax.legend()

plt.show()

# ==========================================================
# Class Distribution
# ==========================================================

for i, cls in enumerate(encoder.classes_):

    print(

        cls,

        ":",

        np.sum(labels == i)

    )

# ==========================================================
# Save Features
# ==========================================================

np.save(

    "ConViTX_Features.npy",

    features

)

print("Deep features saved successfully.")