# -*- coding: utf-8 -*-
"""Mobilenet v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10avETM_6VEiAuOs7PRMq3rnezm9cBZEF
"""

# ============================================================
# POTATO DISEASE CLASSIFICATION
# MobileNetV2 ONLY
# Classes: Early Blight, Late Blight, Healthy
# ============================================================

import os
import zipfile
import shutil
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import ImageDataGenerator

print("TensorFlow:", tf.__version__)

# ============================================================
# 1. ZIP PATH
# ============================================================

ZIP_PATH = "/content/Potato.zip"
EXTRACT_PATH = "/content/Potato_dataset"

# Clean previous extraction
if os.path.exists(EXTRACT_PATH):
    shutil.rmtree(EXTRACT_PATH)

os.makedirs(EXTRACT_PATH, exist_ok=True)

# ============================================================
# 2. EXTRACT COMPLETE ZIP
# ============================================================

if not os.path.isfile(ZIP_PATH):
    raise FileNotFoundError(
        f"Potato ZIP not found: {ZIP_PATH}"
    )

print("ZIP:", ZIP_PATH)
print("Extracting...")

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_PATH)

print("Extraction completed.")

# ============================================================
# 3. FIND ACTUAL CLASS FOLDER
# ============================================================

IMAGE_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".webp"
)

def find_class_root(root):

    candidates = []

    for current_root, dirs, files in os.walk(root):

        image_dirs = []

        for d in dirs:

            folder = os.path.join(
                current_root,
                d
            )

            try:

                has_image = any(
                    f.lower().endswith(IMAGE_EXTENSIONS)
                    for f in os.listdir(folder)
                )

                if has_image:
                    image_dirs.append(d)

            except PermissionError:
                continue

        # Potato dataset should have 3 class folders
        if len(image_dirs) == 3:

            candidates.append(
                (
                    current_root,
                    sorted(image_dirs)
                )
            )

    if not candidates:

        raise RuntimeError(
            "Could not find the 3 Potato class folders."
        )

    # Prefer the shallowest suitable directory
    candidates.sort(
        key=lambda x: x[0].count(os.sep)
    )

    return candidates[0]


DATASET_PATH, classes = find_class_root(
    EXTRACT_PATH
)

print("\nDataset folder:")
print(DATASET_PATH)

print("\nClasses:")
for i, c in enumerate(classes):
    print(i, "->", c)

print("\nNumber of classes:", len(classes))

assert len(classes) == 3, (
    f"Expected 3 Potato classes, found {len(classes)}"
)

# ============================================================
# 4. COUNT IMAGES
# ============================================================

total_images = 0

for cls in classes:

    folder = os.path.join(
        DATASET_PATH,
        cls
    )

    count = sum(
        f.lower().endswith(IMAGE_EXTENSIONS)
        for f in os.listdir(folder)
    )

    print(f"{cls}: {count} images")

    total_images += count

print("\nTotal Potato images:", total_images)

# ============================================================
# IMAGE SETTINGS
# ============================================================

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

# ============================================================
# MOBILENETV2 PREPROCESSING
# ============================================================

preprocess = tf.keras.applications.mobilenet_v2.preprocess_input

# ============================================================
# TRAIN GENERATOR
# ============================================================

train_datagen = ImageDataGenerator(

    preprocessing_function=preprocess,

    validation_split=0.20,

    rotation_range=20,

    width_shift_range=0.10,

    height_shift_range=0.10,

    zoom_range=0.15,

    horizontal_flip=True,

    fill_mode="nearest"
)

# ============================================================
# VALIDATION GENERATOR
# ============================================================

val_datagen = ImageDataGenerator(
    preprocessing_function=preprocess,
    validation_split=0.20
)

train_generator = train_datagen.flow_from_directory(

    DATASET_PATH,

    target_size=IMAGE_SIZE,

    batch_size=BATCH_SIZE,

    classes=classes,

    class_mode="categorical",

    subset="training",

    shuffle=True,

    seed=SEED
)

val_generator = val_datagen.flow_from_directory(

    DATASET_PATH,

    target_size=IMAGE_SIZE,

    batch_size=BATCH_SIZE,

    classes=classes,

    class_mode="categorical",

    subset="validation",

    shuffle=False,

    seed=SEED
)

print("\nTraining images:", train_generator.samples)
print("Validation images:", val_generator.samples)
print("Total:", train_generator.samples + val_generator.samples)

print("\nClass mapping:")
print(train_generator.class_indices)

# ============================================================
# MOBILENETV2 ONLY
# ============================================================

base_model = tf.keras.applications.MobileNetV2(

    input_shape=(224, 224, 3),

    include_top=False,

    weights="imagenet"
)

base_model.trainable = False

inputs = tf.keras.Input(
    shape=(224, 224, 3)
)

x = base_model(
    inputs,
    training=False
)

x = tf.keras.layers.GlobalAveragePooling2D()(x)

x = tf.keras.layers.Dropout(0.30)(x)

outputs = tf.keras.layers.Dense(
    3,
    activation="softmax"
)(x)

model = tf.keras.Model(
    inputs=inputs,
    outputs=outputs,
    name="Potato_MobileNetV2"
)

model.summary()

# ============================================================
# COMPILE
# ============================================================

model.compile(

    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-4
    ),

    loss="categorical_crossentropy",

    metrics=["accuracy"]
)


# ============================================================
# LEARNING RATE SCHEDULER
# ============================================================

def lr_schedule(epoch, lr):

    if epoch < 20:
        return 1e-4

    elif epoch < 60:
        return 5e-5

    elif epoch < 100:
        return 2e-5

    elif epoch < 150:
        return 1e-5

    else:
        return 5e-6


lr_callback = tf.keras.callbacks.LearningRateScheduler(
    lr_schedule,
    verbose=1
)


# ============================================================
# BEST MODEL
# ============================================================

checkpoint = tf.keras.callbacks.ModelCheckpoint(

    "/content/Potato_MobileNetV2_best.keras",

    monitor="val_accuracy",

    mode="max",

    save_best_only=True,

    verbose=1
)


# ============================================================
# TRAIN 200 EPOCHS
# NO EARLY STOPPING
# ============================================================

history = model.fit(

    train_generator,

    validation_data=val_generator,

    epochs=10,

    callbacks=[
        lr_callback,
        checkpoint
    ],

    verbose=1
)

# ============================================================
# LOAD BEST MODEL
# ============================================================

best_model = tf.keras.models.load_model(
    "/content/Potato_MobileNetV2_best.keras"
)

# ============================================================
# PREDICTION
# ============================================================

val_generator.reset()

pred_prob = best_model.predict(
    val_generator,
    verbose=1
)

y_pred = np.argmax(
    pred_prob,
    axis=1
)

y_true = val_generator.classes

print("Predictions:", len(y_pred))
print("True labels:", len(y_true))

# ============================================================
# ACCURACY
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

accuracy = accuracy_score(
    y_true,
    y_pred
)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted"
)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Accuracy  : {accuracy*100:.2f}%")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print(
    classification_report(
        y_true,
        y_pred,
        target_names=classes,
        digits=4
    )
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

import seaborn as sns

cm = confusion_matrix(
    y_true,
    y_pred
)

plt.figure(figsize=(8, 7))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=classes,
    yticklabels=classes
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Potato Disease - MobileNetV2")

plt.tight_layout()
plt.show()

# ============================================================
# ACCURACY AND LOSS PLOTS
# ============================================================

import matplotlib.pyplot as plt

# -----------------------------
# Accuracy
# -----------------------------

plt.figure(figsize=(10, 6))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("MobileNetV2 - Training and Validation Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# -----------------------------
# Loss
# -----------------------------

plt.figure(figsize=(10, 6))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("MobileNetV2 - Training and Validation Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()