# -*- coding: utf-8 -*-
"""RESNET50V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZRqnsRgeZRG8v7p83-W3TWiPJc1GeKT
"""

!pip -q install -U tensorflow scikit-learn matplotlib seaborn

import os
import zipfile
import random
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import Model
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

from tensorflow.keras.applications import ResNet50V2
from tensorflow.keras.applications.resnet_v2 import preprocess_input

from sklearn.metrics import (
    confusion_matrix,
    classification_report
)

print("TensorFlow Version:", tf.__version__)

import zipfile

zip_path = "/content/Potato.zip"
extract_path = "/content"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully.")

import os

dataset_path = "/content/Potato"   # Change if your extracted folder has another name

print(os.listdir(dataset_path))

import os
import shutil
from sklearn.model_selection import train_test_split

SOURCE = dataset_path

DEST = "/content/Potato_Split"

classes = os.listdir(SOURCE)

for cls in classes:

    files = os.listdir(os.path.join(SOURCE, cls))

    train_files, temp_files = train_test_split(
        files,
        test_size=0.20,
        random_state=42,
        shuffle=True
    )

    val_files, test_files = train_test_split(
        temp_files,
        test_size=0.50,
        random_state=42,
        shuffle=True
    )

    for split in ["train","valid","test"]:
        os.makedirs(os.path.join(DEST, split, cls), exist_ok=True)

    for f in train_files:
        shutil.copy(
            os.path.join(SOURCE,cls,f),
            os.path.join(DEST,"train",cls,f)
        )

    for f in val_files:
        shutil.copy(
            os.path.join(SOURCE,cls,f),
            os.path.join(DEST,"valid",cls,f)
        )

    for f in test_files:
        shutil.copy(
            os.path.join(SOURCE,cls,f),
            os.path.join(DEST,"test",cls,f)
        )

print("Dataset split completed.")

import tensorflow as tf

IMAGE_SIZE = (224,224)

BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/Potato_Split/train",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    label_mode="categorical"
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/Potato_Split/valid",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    label_mode="categorical"
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    "/content/Potato_Split/test",
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False,
    label_mode="categorical"
)

class_names = train_ds.class_names

print(class_names)

import numpy as np

print("Classes:", class_names)

for name, ds in [("Train", train_ds), ("Validation", val_ds), ("Test", test_ds)]:
    labels = np.concatenate([np.argmax(y.numpy(), axis=1) for _, y in ds])
    unique, counts = np.unique(labels, return_counts=True)
    print(f"\n{name} Distribution")
    for u, c in zip(unique, counts):
        print(f"{class_names[u]} : {c}")

import numpy as np

print("Classes:", class_names)

for name, ds in [("Train", train_ds), ("Validation", val_ds), ("Test", test_ds)]:
    labels = np.concatenate([np.argmax(y.numpy(), axis=1) for _, y in ds])
    unique, counts = np.unique(labels, return_counts=True)
    print(f"\n{name} Distribution")
    for u, c in zip(unique, counts):
        print(f"{class_names[u]} : {c}")

train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)

val_ds = val_ds.cache().prefetch(AUTOTUNE)

plt.figure(figsize=(12,12))

for images, labels in train_ds.take(1):

    for i in range(9):

        ax = plt.subplot(3,3,i+1)

        plt.imshow(images[i].numpy().astype("uint8"))

        plt.title(class_names[np.argmax(labels[i])])

        plt.axis("off")

plt.show()

data_augmentation = tf.keras.Sequential([

    layers.RandomFlip("horizontal"),

    layers.RandomRotation(0.15),

    layers.RandomZoom(0.2),

    layers.RandomContrast(0.2)

])

plt.figure(figsize=(10,10))

for images, labels in train_ds.take(1):

    first_image = images[0]

    for i in range(9):

        ax = plt.subplot(3,3,i+1)

        augmented = data_augmentation(tf.expand_dims(first_image,0))

        plt.imshow(augmented[0].numpy().astype("uint8"))

        plt.axis("off")

plt.show()

print("="*50)

print("Classes :", class_names)

print("Training batches :", tf.data.experimental.cardinality(train_ds).numpy())

print("Validation batches :", tf.data.experimental.cardinality(val_ds).numpy())

print("Image Size :", IMAGE_SIZE)

print("Batch Size :", BATCH_SIZE)

print("="*50)

from tensorflow.keras import mixed_precision

mixed_precision.set_global_policy("mixed_float16")

print("Policy:", mixed_precision.global_policy())

inputs = tf.keras.Input(shape=(224,224,3))

x = data_augmentation(inputs)

x = preprocess_input(x)

base_model = ResNet50V2(
    include_top=False,
    weights="imagenet",
    input_shape=(224,224,3)
)

# Freeze backbone for Stage 1
base_model.trainable = False

x = base_model(x, training=False)

x = layers.GlobalAveragePooling2D()(x)

x = layers.BatchNormalization()(x)

x = layers.Dropout(0.4)(x)

x = layers.Dense(
    512,
    activation="relu"
)(x)

x = layers.Dropout(0.3)(x)

outputs = layers.Dense(
    len(class_names),
    activation="softmax",
    dtype="float32"      # Required with mixed precision
)(x)

model = tf.keras.Model(
    inputs,
    outputs
)

model.summary()

optimizer = tf.keras.optimizers.AdamW(
    learning_rate=1e-4,
    weight_decay=1e-5
)

loss = tf.keras.losses.CategoricalCrossentropy(
    label_smoothing=0.1
)

model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

checkpoint = ModelCheckpoint(
    "best_resnet50v2.keras",
    monitor="val_accuracy",
    save_best_only=True,
    verbose=1
)

early_stop = EarlyStopping(
    monitor="val_accuracy",
    patience=15,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.2,
    patience=5,
    min_lr=1e-7,
    verbose=1
)

print("Model Ready!")

print("Classes :", class_names)

print("Trainable Parameters:")

print(sum(np.prod(v.shape) for v in model.trainable_weights))

print("Non-trainable Parameters:")

print(sum(np.prod(v.shape) for v in model.non_trainable_weights))

tf.keras.utils.plot_model(
    model,
    show_shapes=True,
    expand_nested=True,
    dpi=120
)

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

# Load full dataset
dataset = tf.keras.utils.image_dataset_from_directory(
    dataset_path,
    image_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=SEED,
    label_mode="categorical"
)

class_names = dataset.class_names

# Count batches
total_batches = tf.data.experimental.cardinality(dataset).numpy()

train_batches = int(0.8 * total_batches)
val_batches = int(0.1 * total_batches)
test_batches = total_batches - train_batches - val_batches

# Split
train_ds = dataset.take(train_batches)

remaining = dataset.skip(train_batches)

val_ds = remaining.take(val_batches)

test_ds = remaining.skip(val_batches)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds = val_ds.cache().prefetch(AUTOTUNE)
test_ds = test_ds.cache().prefetch(AUTOTUNE)

print("Classes:", class_names)
print("Training batches:", tf.data.experimental.cardinality(train_ds).numpy())
print("Validation batches:", tf.data.experimental.cardinality(val_ds).numpy())
print("Testing batches:", tf.data.experimental.cardinality(test_ds).numpy())

INITIAL_EPOCHS = 15

history_initial = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=INITIAL_EPOCHS,
    callbacks=[
        checkpoint,
        early_stop,
        reduce_lr
    ]
)

base_model.trainable = True

# Freeze only the first 100 layers
for layer in base_model.layers[:100]:
    layer.trainable = False

print("Trainable Layers:",
      sum([layer.trainable for layer in base_model.layers]))

model.compile(
    optimizer=tf.keras.optimizers.AdamW(
        learning_rate=1e-5,
        weight_decay=1e-5
    ),

    loss=tf.keras.losses.CategoricalCrossentropy(
        label_smoothing=0.1
    ),

    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

FINE_TUNE_EPOCHS = 105

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    initial_epoch=history_initial.epoch[-1] + 1,
    epochs=INITIAL_EPOCHS + FINE_TUNE_EPOCHS,
    callbacks=[
        checkpoint,
        early_stop,
        reduce_lr
    ]
)

best_model = tf.keras.models.load_model(
    "best_resnet50v2.keras"
)

print("Best model loaded successfully.")

best_model.save("Potato_ResNet50V2_Final.keras")

print("Final model saved!")

train_acc = history_initial.history["accuracy"] + history_fine.history["accuracy"]

val_acc = history_initial.history["val_accuracy"] + history_fine.history["val_accuracy"]

plt.figure(figsize=(8,5))

plt.plot(train_acc, label="Training Accuracy")
plt.plot(val_acc, label="Validation Accuracy")

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)

plt.show()

train_loss = history_initial.history["loss"] + history_fine.history["loss"]

val_loss = history_initial.history["val_loss"] + history_fine.history["val_loss"]

plt.figure(figsize=(8,5))

plt.plot(train_loss, label="Training Loss")
plt.plot(val_loss, label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)

plt.show()

loss, accuracy, precision, recall = best_model.evaluate(
    test_ds,
    verbose=1
)

print("=" * 50)
print(f"Test Accuracy : {accuracy*100:.2f}%")
print(f"Precision     : {precision*100:.2f}%")
print(f"Recall        : {recall*100:.2f}%")
print("=" * 50)

import tensorflow as tf

best_model = tf.keras.models.load_model("best_resnet50v2.keras")

print("Best model loaded successfully.")

loss, accuracy, precision, recall = best_model.evaluate(
    test_ds,
    verbose=1
)

print("="*60)
print(f"Test Loss      : {loss:.4f}")
print(f"Test Accuracy  : {accuracy*100:.2f}%")
print(f"Precision      : {precision*100:.2f}%")
print(f"Recall         : {recall*100:.2f}%")
print("="*60)

import numpy as np

y_true = []
y_pred = []
y_prob = []

for images, labels in test_ds:

    predictions = best_model.predict(images, verbose=0)

    y_true.extend(np.argmax(labels.numpy(), axis=1))

    y_pred.extend(np.argmax(predictions, axis=1))

    y_prob.extend(predictions)

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

plt.imshow(cm, cmap="Blues")

plt.title("Confusion Matrix")

plt.colorbar()

tick_marks = np.arange(len(class_names))

plt.xticks(tick_marks, class_names, rotation=45)

plt.yticks(tick_marks, class_names)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(
            j,
            i,
            str(cm[i, j]),
            ha="center",
            color="black"
        )

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.tight_layout()

plt.show()